### ISSUE TITLE
certificates

### ISSUE THREAD

**Issue by crazyants** [austinejei/sidekick#2]
Hi,OAuthServer must be certificates?

**Comment by austinejei** [comment]
No @crazyants, there are no certificates involved.

**Comment by crazyants** [comment]
Hi,In the authorize method has no  redirection Url,

`public async Task<ActionResult> CallBack(string code)`

and how to generate a code 
`HttpContent content = new FormUrlEncodedContent(new Dictionary<string,string>
                {
                    {"code",code},
                    {"client_id","354yeghdsfc"},
                    {"client_secret","ytfghnfg454"},
                    {"grant_type","authorization_code"},
                    {"scope","user.profile emails.send"},
                    {"redirect_uri","http://localhost/WebApplication1/oauthclient/callback"}
                });
 var result = await client.PostAsync(new Uri("http://localhost:25913/oauth/token"), content);`

**Comment by austinejei** [comment]
Hello @crazyants this line "{"redirect_uri","http://localhost/WebApplication1/oauthclient/callback"}" covers it. Unless i haven't understood your concern well-enough.
